### PR TITLE
more clear stating wedo is a ble device

### PR DESCRIPTION
**Pull request by n3storm**
and some other minor contribution

### CODE REVIEW

**Comment by n3storm** [comment]
I am afraid "compatible chinese device" doesn't have any other identifier. Bluetooth identifier is as "officially" expected, no box name, no paper. Just from an aliexpress/alibaba shop.

Making more visible that WEDO is a BLE device is the very reason to start a pull: I didn't know WEDO is a BLE device nor my chinese copy so it took me time before running: bluepy_helper_cap. Do you think any other way to make this characteristic it more visible?

**Comment by kawasaki** [comment]
Ah, I think now I understand your pain point. BLE is the newer technology. I think non-BLE devices is will be rare over time. Actulaly, LEGO EV3 is the only one non-BLE device in the device list. So I think the step guide about bluepy_helper_cap is not good. It should guide to run not for BLE devices, but for all devices except LEGO EV3. I will pull your changes, and do some more edit on top of it.

I didn't know that the LEGO compatible devices are available at Aliexpress :)  Regarding the wording, "chinese" sound a little bit weird, so I may remove that word.

**Comment by kawasaki** [comment]
@n3storm I pulled your changes, and made one commit on top of it to address your pain point. Thanks for the feedbacks!

**Comment by n3storm** [comment]
Thanks :)

**Pull request merged**
